Apteka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka;
using Apteka.Controllers;
using Apteka.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Routing;
using System.Web.Security;
using Apteka.Common;

namespace Apteka.Controllers
{    
    public class HomeController : Controller
    {
        private db_lekiContext db = new db_lekiContext();

        public ActionResult Index()
        {
            var cart = Apteka.Logic.ShoppingCart.GetCart(this.HttpContext);

            var produktyTop4 = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).OrderBy(x=>x.Id).ToList().Take(4);

            // Set up our ViewModel
            var viewModel = new Apteka.ViewModels.ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartTotalNumber = cart.GetCount(),
                Products = produktyTop4
            };

            return View(viewModel);
        }

        public ActionResult About()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult SimpleVerticalMenu()
        {
            //The menu datasource. 
            var items = MenuItems.Get();

            string action = ControllerContext.ParentActionViewContext.RouteData.Values["action"].ToString();
            string controller = ControllerContext.ParentActionViewContext.RouteData.Values["controller"].ToString();

            items.ForEach(i => i.MenuItems.ForEach(m =>
            {
                if (m.Controller.ToLower().Equals(controller.ToLower()) && m.Action.ToLower().Equals(action.ToLower()))
                {
                    m.Selected = i.Active = true;
                }
            }));

            return PartialView(items);
        }
    }
}

Apteka/Controllers/ProduktyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka;

namespace Apteka.Controllers
{ 
    public class ProduktyController : Controller
    {
        private db_lekiContext db = new db_lekiContext();

        //
        // GET: /Produkty/

        public ViewResult Index()
        {
            var t_produkty = db.t_produkty.Include(t => t.t_sklepy).Include(t => t.t_leki).Where(a => a.t_sklepy.t_users.Login == User.Identity.Name);
            return View(t_produkty.ToList());
        }

        //
        // GET: /Produkty/Details/5

        public ViewResult Details(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            return View(t_produkty);
        }

        //
        // GET: /Produkty/Create

        public ActionResult Create()
        {            
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char");
            return View();
            // <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
        } 

        //
        // POST: /Produkty/Create

        [HttpPost]
        public ActionResult Create(t_produkty t_produkty)
        {
            var asd = db.t_sklepy.Where(b => b.t_users.Login == User.Identity.Name);

            if (ModelState.IsValid)
            {
                t_produkty.sklep_id = asd.First().Id;
                db.t_produkty.Add(t_produkty);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }
        
        //
        // GET: /Produkty/Edit/5
 
        public ActionResult Edit(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }

        //
        // POST: /Produkty/Edit/5

        [HttpPost]
        public ActionResult Edit(t_produkty t_produkty)
        {
            var asd = db.t_sklepy.Where(b => b.t_users.Login == User.Identity.Name);

            if (ModelState.IsValid)
            {
                t_produkty.sklep_id = asd.First().Id;
                db.Entry(t_produkty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }

        //
        // GET: /Produkty/Delete/5
 
        public ActionResult Delete(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            return View(t_produkty);
        }

        //
        // POST: /Produkty/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            t_produkty t_produkty = db.t_produkty.Find(id);
            db.t_produkty.Remove(t_produkty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Apteka/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka.ViewModels;
using Apteka.Logic;

namespace Apteka.Controllers
{
    public class ShoppingCartController : Controller
    {
        db_lekiContext storeDB = new db_lekiContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartTotalNumber = cart.GetCount()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProdukt = storeDB.t_produkty
                .Single(x => x.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProdukt);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty.t_leki.nazwa_char;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " usunięto z koszyka.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult AddToCartP(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            var produkt = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty;

            int itemCount = cart.GetCount();

            if (itemCount < produkt.ilosc)
            {
                cart.AddToCart(produkt);
                itemCount++;

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " dodano do koszyka.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            else
            {
                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " brak produktu!!!",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }  
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Apteka/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}
<h2>Kontakt</h2>
<p>
     Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultricies pretium dolor rhoncus tincidunt. Aliquam sed purus id lorem placerat convallis. Cras mauris felis, viverra a tempus quis, sodales sed lectus. In rutrum auctor velit, eu tempus elit molestie id. Nullam elit nulla, feugiat vitae interdum eget, consectetur in lectus.
</p>

Apteka/Views/Home/Index.cshtml
@model Apteka.ViewModels.ShoppingCartViewModel
<link href="../../Content/menu/simpleverticalmenu.css" rel="stylesheet" />
<script src="../../Scripts/menu/simpleverticalmenu.js"></script>
           
@{
    ViewBag.Title = "Home Page";
}
@section Advert {
                <div class="cleaner"></div>
                <div id="banner">
                	<a href="#" target="_parent"><img src="/Content/themes/base/images/banner.png" alt="banner" /></a>                
                </div>
                }

<h3>Ostatnio dodane</h3>
<div class="product_box margin_r20">
    @if (Model.Products.ToArray().Count() > 0)
    {
        <a href="#"><img src="/Content/themes/base/images/image_2.png" alt="" width="220" height="165" /></a>
        <h3>@Model.Products.ToArray()[0].t_leki.nazwa_char</h3>
        <p class="price">Cena: <span>@Model.Products.ToArray()[0].cena PLN</span></p>
        @Html.ActionLink("Szczegóły", "Details", "Produkty", new { id = Model.Products.ToArray()[0].Id }, new { @class = "detail" }) @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = Model.Products.ToArray()[0].Id, returnUrl = Request.Url }, new { @class = "addtocard" })
    }
    <div class="cleaner"></div>
</div>

<div class="product_box">
    @if (Model.Products.ToArray().Count() > 1)
    {                
        <a href="#"><img src="/Content/themes/base/images/image_3.png" alt="Red Bell" width="220" height="165" /></a>
        <h3>@Model.Products.ToArray()[1].t_leki.nazwa_char</h3>
        <p class="price">Cena: <span>@Model.Products.ToArray()[1].cena PLN</span></p>
        @Html.ActionLink("Szczegóły", "Details", "Produkty", new { id = Model.Products.ToArray()[1].Id }, new { @class = "detail" }) @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = Model.Products.ToArray()[1].Id, returnUrl = Request.Url }, new { @class = "addtocard" })
    }                    
    <div class="cleaner"></div>
</div>
                    
                    
<div class="product_box margin_r20">
    @if (Model.Products.ToArray().Count() > 2)
    {        	
        <a href="#" target="_parent"><img src="/Content/themes/base/images/image_4.png" alt="Christmas Gift" width="220" height="165" /></a>
        <h3>@Model.Products.ToArray()[2].t_leki.nazwa_char</h3>
        <p class="price">Cena: <span>@Model.Products.ToArray()[2].cena PLN</span></p>
        @Html.ActionLink("Szczegóły", "Details", "Produkty", new { id = Model.Products.ToArray()[2].Id }, new { @class = "detail" }) @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = Model.Products.ToArray()[2].Id, returnUrl = Request.Url }, new { @class = "addtocard" })
    }                   
    <div class="cleaner"></div>
</div>
                    
<div class="product_box">
    @if (Model.Products.ToArray().Count() > 3)
    {
        <a href="#" target="_parent"><img src="/Content/themes/base/images/image_1.png" alt="Christmas Bell" width="220" height="165" /></a>
        <h3>@Model.Products.ToArray()[3].t_leki.nazwa_char</h3>
        <p class="price">Cena: <span>@Model.Products.ToArray()[3].cena PLN</span></p>
        @Html.ActionLink("Szczegóły", "Details", "Produkty", new { id = Model.Products.ToArray()[3].Id }, new { @class = "detail" }) @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = Model.Products.ToArray()[3].Id, returnUrl = Request.Url }, new { @class = "addtocard" })
    }                    
    <div class="cleaner"></div>
</div>
<div class="cleaner"></div>