Apteka/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Apteka.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<t_CartItems> CartItems { get; set; }
        public decimal CartTotal { get; set; }
        public int CartTotalNumber { get; set; }
        public IEnumerable<t_produkty> Products { get; set; }
        public t_users User { get; set; }
    }
}

Apteka/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka.ViewModels;
using Apteka.Logic;
using System.Data;
using System.Xml;
using System.Net.Mail;
using System.Net;

namespace Apteka.Controllers
{
    public class CheckoutController : Controller
    {
        private db_lekiContext db = new db_lekiContext();
        //
        // GET: /Checkout/

        public ActionResult AddressAndPayment()
        {
            if (User.Identity.IsAuthenticated)
            {
                var model = new ShoppingCartViewModel();
                var cart = ShoppingCart.GetCart(this.HttpContext);

                model.User = db.t_users.Where(x => x.Login == User.Identity.Name).Single();
                model.CartItems = cart.GetCartItems();
                model.CartTotal = cart.GetTotal();
                model.CartTotalNumber = cart.GetCount();
                return View(model);
            }
            else
            {
                return RedirectToAction("LogOn", "Account");
            }
        }

        [HttpPost]
        public ActionResult AddressAndPayment(string paymentOption, string transportOption)
        {
            var model = new ShoppingCartViewModel();
            var cart = ShoppingCart.GetCart(this.HttpContext);
            model.CartItems = cart.GetCartItems();

            var prod = model.CartItems.Select(x => x.t_produkty.Id);
            //for kazdy produkt
            foreach (var p in prod)
            {
                //sprawdz czy sa te produkty
                var dbProd = db.t_produkty.Where(x => x.Id == p).Single();
                if (dbProd.ilosc < model.CartItems.Where(x => x.ProduktId == p).Single().Count)
                {
                    return RedirectToAction("Index","Home");//informacja o bledzie
                }
                else
                {
                    //zmiejszyc ilosc lub usunac (o ilosc kupionych)
                    if (dbProd.ilosc == model.CartItems.Where(x => x.ProduktId == p).Single().Count)
                    {
                        db.Entry(dbProd).State = EntityState.Deleted;
                        db.SaveChanges();
                    }
                    else
                    {
                        dbProd.ilosc -= model.CartItems.Where(x => x.ProduktId == p).Single().Count;
                        db.Entry(dbProd).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }

            }

            var shops = model.CartItems.Select(x => x.t_produkty.sklep_id).Distinct();
            //for kazdy sklep
            foreach (var s in shops)
            {
                //wyciagnac produkty
                var prodByShop = model.CartItems.Where(x => x.t_produkty.sklep_id == s);
                //podac adres
                var userAddr = db.t_users.Where(x => x.Login == User.Identity.Name).Single();
                //podac opcje przesylki
                string transportOptString;
                switch (transportOption)
                {
                    case "0": transportOptString = "Odbiór własny (0 PLN)";
                        break;
                    case "10": transportOptString = "Przesyłka kurierska (10 PLN)";
                        break;
                    case "7": transportOptString = "Przesyłka pocztowa (list polecony) (7 PLN)";
                        break;
                    case "5": transportOptString = "Przesyłka pocztowa (list zwykły) (5 PLN)";
                        break;
                    default: transportOptString = "Inny typ wysyłki (NaNa PLN)";
                        break;
                }
                //podac opcje zaplaty
                string paymentOptString;
                switch (paymentOption)
                {
                    case "0": paymentOptString = "W aptece (0 PLN)";
                        break;
                    case "5": paymentOptString = "Przelew na konto (5 PLN)";
                        break;
                    case "10": paymentOptString = "Przy odbiorze (10 PLN)";
                        break;
                    default: paymentOptString = "Inny forma płatności (NaNa PLN)";
                        break;
                }
                //parsowanie do xmla
                XmlDocument doc = new XmlDocument();
                XmlDeclaration declaration = doc.CreateXmlDeclaration("1.0", "ISO-8859-1", null);
                doc.AppendChild(declaration);
                //produkty (xml)
                XmlElement el = (XmlElement)doc.AppendChild(doc.CreateElement("Produkty"));
                
                foreach (var pp in prodByShop)
                {
                    XmlElement elP = (XmlElement)el.AppendChild(doc.CreateElement("IdProduktu"+Convert.ToString(pp.ProduktId)));
                    elP.AppendChild(doc.CreateElement("Nazwa")).InnerText = pp.t_produkty.t_leki.nazwa_char;
                    elP.AppendChild(doc.CreateElement("Ilosc")).InnerText = Convert.ToString(pp.Count);
                    elP.AppendChild(doc.CreateElement("Cena")).InnerText = Convert.ToString(pp.t_produkty.cena);
                }
                //transport (xml)
                el.AppendChild(doc.CreateElement("Transport")).InnerText = transportOptString;
                //platnosc (xml)
                el.AppendChild(doc.CreateElement("Platnosc")).InnerText = paymentOptString;
                //adres wysylki (xml)
                XmlElement elW = (XmlElement)el.AppendChild(doc.CreateElement("AdresWysylki"));
                elW.AppendChild(doc.CreateElement("Imie")).InnerText = userAddr.Imie;
                elW.AppendChild(doc.CreateElement("Nazwisko")).InnerText = userAddr.Nazwisko;
                elW.AppendChild(doc.CreateElement("Adres")).InnerText = userAddr.Ulica+" "+userAddr.KodPocztowy+" "+userAddr.Miasto+" "+userAddr.NumerDomu+"/"+userAddr.NumerMieszkania;
                elW.AppendChild(doc.CreateElement("email")).InnerText = userAddr.email;
                Console.WriteLine(doc.OuterXml);
                //dodac zamowienie (user_id,sklep_id,xml,status)
                t_zamowienia NewZam = new t_zamowienia();
                NewZam.lek_data = doc.InnerXml;
                NewZam.sklep_id = s;
                NewZam.status = "nowe";
                NewZam.user_id = userAddr.Id;
                db.Entry(NewZam).State = EntityState.Added;
                db.SaveChanges();

                //wyslac jakiegos maila do kupujacego
                var usr = db.t_users.First(a => a.Login == User.Identity.Name);
                MailMessage mail = new MailMessage();
                NetworkCredential basicCredential =
                new NetworkCredential("aptegropl", "1q2w3e4r%T");
                SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");
                mail.From = new MailAddress("aptegropl@gmail.com");
                mail.To.Add(usr.email);
                mail.Subject = "Potwierdzenie zakupu";
                mail.IsBodyHtml = true;
                mail.Body = "Nazwa sklepu: "+ db.t_sklepy.Where(x=>x.Id==s).Single().Nazwa
                    +". Status zamówienia: <b>"+ NewZam.status+"</b>";

                SmtpServer.Host = "smtp.gmail.com";
                //SmtpServer.EnableSsl = true;
                SmtpServer.UseDefaultCredentials = false;
                SmtpServer.Credentials = basicCredential;
                SmtpServer.Send(mail);
            }

            //wyczyscic koszyk
            cart.EmptyCart();

            return RedirectToAction("Index","Home");
        }

    }
}

Apteka/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka.ViewModels;
using Apteka.Logic;

namespace Apteka.Controllers
{
    public class ShoppingCartController : Controller
    {
        db_lekiContext storeDB = new db_lekiContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartTotalNumber = cart.GetCount()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProdukt = storeDB.t_produkty
                .Single(x => x.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProdukt);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty.t_leki.nazwa_char;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " usunięto z koszyka.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult AddToCartP(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            var produkt = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty;

            int itemCount = cart.GetCount();

            if (itemCount < produkt.ilosc)
            {
                cart.AddToCart(produkt);
                itemCount++;

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " dodano do koszyka.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            else
            {
                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " brak produktu!!!",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }  
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Apteka/Views/ShoppingCart/Index.cshtml
@model Apteka.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}
<script src="/Scripts/jquery-1.4.4.min.js"
type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
            });

            $(".AddLink").click(function () {
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/ShoppingCart/AddToCartP", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
                }
            });
    });
</script>
<h3>
    Podgląd Twojego koszyka:
 </h3>
 @if (Model.CartTotalNumber > 0)
 {
    <p class="button">
        @Html.ActionLink("Zatwierdź>>", "AddressAndPayment", "Checkout", new { returnUrl = Request.Url }, null)
    </p>
    <div id="update-message">
    </div>
    <table>
        <tr>
            <th>
                Nazwa leku
            </th>
            <th>
                Cena (każdy)
            </th>
            <th>
                Ilość
            </th>
            <th></th>
        </tr>
        @foreach (var item in
    Model.CartItems)
        {
            <tr id="row-@item.RecordId">
                <td>
                    @Html.ActionLink(item.t_produkty.t_leki.nazwa_char,
    "Details", "Produkty", new { id = item.ProduktId }, null)
                </td>
                <td>
                    @item.t_produkty.cena
                </td>
                <td id="item-count-@item.RecordId">
                    @item.Count
                </td>
                <td>
                    <a href="#" class="RemoveLink"
    data-id="@item.RecordId">Usuń</a>
                </td>
                <td>
                    <a href="#" class="AddLink"
    data-id="@item.RecordId">Dodaj</a>
                </td>
            </tr>
        }
        <tr>
            <td>
                W sumie:
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td id="cart-total">
                @Model.CartTotal
            </td>
        </tr>
    </table>
 }
 else
 {
     <h4>Niestety Twój koszyk jest pusty... Wybierz jakieś produkty.</h4>
     <br />
 }