Apteka/Controllers/DiscountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apteka.Controllers
{
    public class DiscountsController : Controller
    {
        //
        // GET: /Discounts/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Apteka/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apteka.Controllers
{
    public class RulesController : Controller
    {
        //
        // GET: /Rules/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Apteka/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka.ViewModels;
using Apteka.Logic;

namespace Apteka.Controllers
{
    public class ShoppingCartController : Controller
    {
        db_lekiContext storeDB = new db_lekiContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartTotalNumber = cart.GetCount()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProdukt = storeDB.t_produkty
                .Single(x => x.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProdukt);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty.t_leki.nazwa_char;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " usunięto z koszyka.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult AddToCartP(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            var produkt = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty;

            int itemCount = cart.GetCount();

            if (itemCount < produkt.ilosc)
            {
                cart.AddToCart(produkt);
                itemCount++;

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " dodano do koszyka.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            else
            {
                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " brak produktu!!!",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }  
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Apteka/Views/Shared/SimpleVerticalMenu.cshtml
@model IList<Apteka.Models.SimpleVerticalMenuModel>
<div class="vmenu">
    @foreach (var menuItem in Model)
    {
        <div class="vmenu-section">@menuItem.Text</div>
        
        <div class="@(menuItem.Active ? "active" : "inactive")">
            <ul class="vmenu-list">
                @foreach (var item in menuItem.MenuItems)
                {
                    <li>@Html.ActionLink(item.Text, item.Action, item.Controller, null, new { @class = item.Selected ? "selected" : "notselected" })</li>
                }
            </ul>
        </div>
    }
</div>

Apteka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/templatemo_style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>    
</head>
<body>
    <div class="page">
        <div id="templatemo_body_wrapper">
	        <div id="templatemo_wrapper">
                <div id="templatemo_header">
    	
                    <div id="site_title">
                        <a href="/" target="_parent">
                            <img src="@Url.Content("~/Content/themes/base/images/templatemo_logo.png")" alt="logo" />
                            <span>Twoja Internetowa Apteka</span>
                        </a>
                    </div>
            
                    <div id="logindisplay">
                        @Html.Partial("_LogOnPartial")
                    </div>
                    <div id="shopping_cart_box">
            	        @Html.Partial("_ShopingCart")
                    </div>       
        </div> <!-- end of templatemo_header -->
        <div id="templatemo_menu">
        
        	<div id="search_box">
              <form action="/Category" method="post">
                    <input type="text" value="" name="SearchString" size="10" id="input_field" title="nazwa" />
                    <input type="submit" name="login" value="Szukaj" alt="login" id="submit_btn" title="Login" />
              </form>
            </div>  
                  
            <ul>
                <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                <li>@Html.ActionLink("Promocje", "Index", "Discounts")</li>
                <li>@Html.ActionLink("FAQ", "Index", "FAQ")</li>
                @if (!string.IsNullOrEmpty(User.Identity.Name))
                {
                    <li>@Html.ActionLink("Twoje Konto", "EdycjaDanych", "Account")</li>
                }
                <li>@Html.ActionLink("Regulamin", "Index", "Rules")</li>
                <li>@Html.ActionLink("Kontakt", "About", "Home")</li>
                    
            </ul>    	
        
        </div> <!-- end of templatemo_menu -->

        <div id="templatemo_content_wrapper">      
        @Html.Partial("_SideBar") 

        <section id="main">

        <div id="templatemo_content">
        @RenderSection("Advert", required: false)
            <div id="content_top"></div>
            <div id="content_middle">
                @RenderBody()
            </div>
            <div id="content_bottom"></div>
        </div>
        </section>


      <div class="cleaner"></div>
      <div id="templatemo_footer_wrapper">

	    <div id="templatemo_footer">
    
            <ul class="footer_menu">
                <li><a href="#" class="current">Today's Specials</a></li>
                <li><a href="#" target="_blank">Web Design</a></li>
                <li><a href="#" target="_parent">Templates</a></li>
                <li><a href="#">Wish Lists</a></li>
                <li><a href="#">Shipping Rates</a></li>
                <li><a href="#">Return Policies</a></li>
                <li><a href="#">Your Account</a></li>
                <li class="last_menu"><a href="#">Help</a></li>
            </ul> 
    
            Copyright © 2013 <a href="#">Aptegro</a>
        
    	    <div class="cleaner"></div>
        </div> <!-- end of footer -->
    </div> <!-- end of templatmeo_footer_wrapper -->
        </div>
</body>
</html>

Apteka/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Witaj <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Wyloguj", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Zaloguj", "LogOn", "Account") ]
}

Apteka/Views/Shared/_ShopingCart.cshtml
@{
    ViewBag.Title = "_ShopingCart";

    var shopingCart = Apteka.Logic.ShoppingCart.GetCart(Context);
}

<h3>@Html.ActionLink("Koszyk zakupów", "Index", "ShoppingCart")</h3>
<p>Wszystkich: <span><b>@shopingCart.GetCount()</b> produktów</span> w koszyku</p>

Apteka/Views/Shared/_SideBar.cshtml
<link href="@Url.Content("~/Content/menu/simpleverticalmenu.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/menu/simpleverticalmenu.js")" type="text/javascript"></script>

 <div class="templatemo_sidebar_wrapper float_l">
    <div class="templatemo_sidebar_top"></div>
    <div class="templatemo_sidebar">
                
        <div class="sidebar_box">
            
            <h2>Kategorie</h2>
            <div class="sidebar_box_content">
            @{ Html.RenderAction("SimpleVerticalMenu", "Home"); }       
                </div>
    
        </div>
                
        <div class="sidebar_box">
                    
            <h2>Mega Promocje:</h2>
                        
        <div class="sidebar_box_content">
                        
                <a href="#"><img src="/Content/themes/base/images/image_3.png" alt="product" width="160" height="120" /></a>
                            
                <p>Praesent mi mi, suscipit non aliquam</p>
                            
                <div class="discount"><span>30% taniej!</span> | @Html.ActionLink("Dowiedz się więcej!", "Index", "Discounts")</div>
                        
                <div class="cleaner"></div>
            </div>
                        
        </div>      
                
    </div> <div class="templatemo_sidebar_bottom"></div> <!-- end of sidebar -->
</div> <!-- end of templatemo_sidebar_wrapper --> 