Apteka/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka;
using Apteka.Controllers;
using Apteka.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Routing;
using System.Web.Security;
using Apteka.Common;


namespace Apteka.Controllers
{
    public class CategoryController : Controller
    {
        private db_lekiContext db = new db_lekiContext();

        public ActionResult Index(string searchString, string sortModel)
        {
            ViewBag.Message = "Wszystkie leki";
            ViewBag.ActionName = "Index";
            ViewBag.Category = "Nazwa";

            var produkty = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).Where(c => c.t_leki.t_informacje.bez_rec_bool == true);

            var synonimy = produkty;

            List<t_produkty> lista = new List<t_produkty>();

            if (!String.IsNullOrEmpty(searchString))
            {
                produkty = produkty.Where(a => a.t_leki.nazwa_char.Contains(searchString));
                synonimy = synonimy.Where(b => b.t_leki.t_informacje.t_syno.nazwa_char.Equals(searchString));

                foreach (var p in synonimy)
                {
                    lista.Add(p);
                }
                foreach (var p in produkty)
                {
                    lista.Add(p);
                }
            }
            else
            {
                lista = produkty.ToList();
            }

            switch (sortModel)
            {
                case "cena": lista = lista.OrderBy(x => x.cena).ToList();
                    break;
                case "ilosc": lista = lista.OrderBy(x => x.ilosc).ToList();
                    break;
                case "cenailosc": lista = lista.OrderBy(x => x.cena).ThenBy(x=>x.ilosc).ToList();
                    break;                                
                case "sklep": lista = lista.OrderBy(x => x.t_sklepy.Nazwa).ToList();
                    break;
                case "producent": lista = lista.OrderBy(x => x.t_leki.t_producenci.nazwa_char).ToList();
                    break;
                case "internaz": lista = lista.OrderBy(x => x.t_leki.t_informacje.t_inter.nazwa_char).ToList();
                    break;
                case "nazwa": lista = lista.OrderBy(x => x.t_leki.nazwa_char).ToList();
                    break;
            }

            return View(lista);
        }

        public ActionResult Kosmetyki(string searchString, string sortModel)
        {
            ViewBag.Message = "Kosmetyki";
            ViewBag.ActionName = "Kosmetyki";
            ViewBag.Category = "Nazwa";
            
            var produkty = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).Where(c => c.t_leki.t_informacje.kosmetyk_bool == true && c.t_leki.t_informacje.bez_rec_bool == true);

            var synonimy = produkty;

            List<t_produkty> lista = new List<t_produkty>();

            if (!String.IsNullOrEmpty(searchString))
            {
                produkty = produkty.Where(a => a.t_leki.nazwa_char.Contains(searchString));
                synonimy = synonimy.Where(b => b.t_leki.t_informacje.t_syno.nazwa_char.Equals(searchString));

                foreach (var p in synonimy)
                {
                    lista.Add(p);
                }
                foreach (var p in produkty)
                {
                    lista.Add(p);
                }
            }
            else
            {
                lista = produkty.ToList();
            }

            switch (sortModel)
            {
                case "cena": lista = lista.OrderBy(x => x.cena).ToList();
                    break;
                case "ilosc": lista = lista.OrderBy(x => x.ilosc).ToList();
                    break;
                case "cenailosc": lista = lista.OrderBy(x => x.cena).ThenBy(x => x.ilosc).ToList();
                    break;
            }

            return View("index", lista);
        }

        public ActionResult Dieta(string searchString, string sortModel)
        {
            ViewBag.Message = "Dieta";
            ViewBag.ActionName = "Dieta";
            ViewBag.Category = "Nazwa";

            var produkty = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).Where(c => c.t_leki.t_informacje.diet_bool == true && c.t_leki.t_informacje.bez_rec_bool == true);

            var synonimy = produkty;

            List<t_produkty> lista = new List<t_produkty>();

            if (!String.IsNullOrEmpty(searchString))
            {
                produkty = produkty.Where(a => a.t_leki.nazwa_char.Contains(searchString));
                synonimy = synonimy.Where(b => b.t_leki.t_informacje.t_syno.nazwa_char.Equals(searchString));

                foreach (var p in synonimy)
                {
                    lista.Add(p);
                }
                foreach (var p in produkty)
                {
                    lista.Add(p);
                }
            }
            else
            {
                lista = produkty.ToList();
            }

            switch (sortModel)
            {
                case "cena": lista = lista.OrderBy(x => x.cena).ToList();
                    break;
                case "ilosc": lista = lista.OrderBy(x => x.ilosc).ToList();
                    break;
                case "cenailosc": lista = lista.OrderBy(x => x.cena).ThenBy(x => x.ilosc).ToList();
                    break;
                case "sklep": lista = lista.OrderBy(x => x.t_sklepy.Nazwa).ToList();
                    break;
                case "producent": lista = lista.OrderBy(x => x.t_leki.t_producenci.nazwa_char).ToList();
                    break;
                case "internaz": lista = lista.OrderBy(x => x.t_leki.t_informacje.t_inter.nazwa_char).ToList();
                    break;
                case "nazwa": lista = lista.OrderBy(x => x.t_leki.nazwa_char).ToList();
                    break;
            }

            return View("index", lista);
        }

        public ActionResult Dezynfekcyjny(string searchString, string sortModel)
        {
            ViewBag.Message = "Dezynfekcyjny";
            ViewBag.ActionName = "Dezynfekcyjny";
            ViewBag.Category = "Nazwa";

            var produkty = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).Where(c => c.t_leki.t_informacje.dezyn_bool == true && c.t_leki.t_informacje.bez_rec_bool == true);

            var synonimy = produkty;

            List<t_produkty> lista = new List<t_produkty>();

            if (!String.IsNullOrEmpty(searchString))
            {
                produkty = produkty.Where(a => a.t_leki.nazwa_char.Contains(searchString));
                synonimy = synonimy.Where(b => b.t_leki.t_informacje.t_syno.nazwa_char.Equals(searchString));

                foreach (var p in synonimy)
                {
                    lista.Add(p);
                }
                foreach (var p in produkty)
                {
                    lista.Add(p);
                }
            }
            else
            {
                lista = produkty.ToList();
            }

            switch (sortModel)
            {
                case "cena": lista = lista.OrderBy(x => x.cena).ToList();
                    break;
                case "ilosc": lista = lista.OrderBy(x => x.ilosc).ToList();
                    break;
                case "cenailosc": lista = lista.OrderBy(x => x.cena).ThenBy(x => x.ilosc).ToList();
                    break;
                case "sklep": lista = lista.OrderBy(x => x.t_sklepy.Nazwa).ToList();
                    break;
                case "producent": lista = lista.OrderBy(x => x.t_leki.t_producenci.nazwa_char).ToList();
                    break;
                case "internaz": lista = lista.OrderBy(x => x.t_leki.t_informacje.t_inter.nazwa_char).ToList();
                    break;
                case "nazwa": lista = lista.OrderBy(x => x.t_leki.nazwa_char).ToList();
                    break;
            }

            return View("index", lista);
        }

        public ActionResult Homeopatyczny(string searchString, string sortModel)
        {
            ViewBag.Message = "Homeopatyczny";
            ViewBag.ActionName = "Homeopatyczny";
            ViewBag.Category = "Nazwa";

            var produkty = db.t_produkty.Include(a => a.t_leki).Include(b => b.t_sklepy).Where(c => c.t_leki.t_informacje.homeo_bool == true && c.t_leki.t_informacje.bez_rec_bool == true);

            var synonimy = produkty;

            List<t_produkty> lista = new List<t_produkty>();

            if (!String.IsNullOrEmpty(searchString))
            {
                produkty = produkty.Where(a => a.t_leki.nazwa_char.Contains(searchString));
                synonimy = synonimy.Where(b => b.t_leki.t_informacje.t_syno.nazwa_char.Equals(searchString));

                foreach (var p in synonimy)
                {
                    lista.Add(p);
                }
                foreach (var p in produkty)
                {
                    lista.Add(p);
                }
            }
            else
            {
                lista = produkty.ToList();
            }

            switch (sortModel)
            {
                case "cena": lista = lista.OrderBy(x => x.cena).ToList();
                    break;
                case "ilosc": lista = lista.OrderBy(x => x.ilosc).ToList();
                    break;
                case "cenailosc": lista = lista.OrderBy(x => x.cena).ThenBy(x => x.ilosc).ToList();
                    break;
                case "sklep": lista = lista.OrderBy(x => x.t_sklepy.Nazwa).ToList();
                    break;
                case "producent": lista = lista.OrderBy(x => x.t_leki.t_producenci.nazwa_char).ToList();
                    break;
                case "internaz": lista = lista.OrderBy(x => x.t_leki.t_informacje.t_inter.nazwa_char).ToList();

Apteka/Controllers/ProduktyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka;

namespace Apteka.Controllers
{ 
    public class ProduktyController : Controller
    {
        private db_lekiContext db = new db_lekiContext();

        //
        // GET: /Produkty/

        public ViewResult Index()
        {
            var t_produkty = db.t_produkty.Include(t => t.t_sklepy).Include(t => t.t_leki).Where(a => a.t_sklepy.t_users.Login == User.Identity.Name);
            return View(t_produkty.ToList());
        }

        //
        // GET: /Produkty/Details/5

        public ViewResult Details(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            return View(t_produkty);
        }

        //
        // GET: /Produkty/Create

        public ActionResult Create()
        {            
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char");
            return View();
            // <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
        } 

        //
        // POST: /Produkty/Create

        [HttpPost]
        public ActionResult Create(t_produkty t_produkty)
        {
            var asd = db.t_sklepy.Where(b => b.t_users.Login == User.Identity.Name);

            if (ModelState.IsValid)
            {
                t_produkty.sklep_id = asd.First().Id;
                db.t_produkty.Add(t_produkty);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }
        
        //
        // GET: /Produkty/Edit/5
 
        public ActionResult Edit(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }

        //
        // POST: /Produkty/Edit/5

        [HttpPost]
        public ActionResult Edit(t_produkty t_produkty)
        {
            var asd = db.t_sklepy.Where(b => b.t_users.Login == User.Identity.Name);

            if (ModelState.IsValid)
            {
                t_produkty.sklep_id = asd.First().Id;
                db.Entry(t_produkty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.lek_id = new SelectList(db.t_leki.Where(c => c.t_informacje.bez_rec_bool == true), "pk_lek_id_num", "nazwa_char", t_produkty.lek_id);
            return View(t_produkty);
        }

        //
        // GET: /Produkty/Delete/5
 
        public ActionResult Delete(int id)
        {
            t_produkty t_produkty = db.t_produkty.Find(id);
            return View(t_produkty);
        }

        //
        // POST: /Produkty/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            t_produkty t_produkty = db.t_produkty.Find(id);
            db.t_produkty.Remove(t_produkty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Apteka/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apteka.ViewModels;
using Apteka.Logic;

namespace Apteka.Controllers
{
    public class ShoppingCartController : Controller
    {
        db_lekiContext storeDB = new db_lekiContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal(),
                CartTotalNumber = cart.GetCount()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProdukt = storeDB.t_produkty
                .Single(x => x.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProdukt);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty.t_leki.nazwa_char;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " usunięto z koszyka.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult AddToCartP(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            var produkt = storeDB.t_CartItems
                .Single(item => item.RecordId == id).t_produkty;

            int itemCount = cart.GetCount();

            if (itemCount < produkt.ilosc)
            {
                cart.AddToCart(produkt);
                itemCount++;

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " dodano do koszyka.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }
            else
            {
                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(produkt.t_leki.nazwa_char) +
                        " brak produktu!!!",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = itemCount,
                    DeleteId = id
                };
                return Json(results);
            }  
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Apteka/Views/Produkty/Create.cshtml
@model Apteka.t_produkty

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj produkt</h2>


<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Produkty apteki</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.cena)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cena)
            @Html.ValidationMessageFor(model => model.cena)
        </div>        

        <div class="editor-label">
            @Html.LabelFor(model => model.lek_id, "t_leki")
        </div>
        <div class="editor-field">
            @Html.DropDownList("lek_id", String.Empty)
            @Html.ValidationMessageFor(model => model.lek_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ilosc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ilosc)
            @Html.ValidationMessageFor(model => model.ilosc)
        </div>

        <p>
            <input type="submit" value="Dodaj" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

Apteka/Views/Produkty/Delete.cshtml
@model Apteka.t_produkty

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć?</h3>
<fieldset>
    <legend>Produkty apteki.</legend>

    <div class="display-label">cena</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.cena)
    </div>

    <div class="display-label">t_sklepy</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.t_sklepy.Nazwa)
    </div>

    <div class="display-label">t_leki</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.t_leki.nazwa_char)
    </div>

    <div class="display-label">ilosc</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ilosc)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Usuń" /> |
        @Html.ActionLink("Powrót", "Index")
    </p>
}

Apteka/Views/Produkty/Details.cshtml
@model Apteka.t_produkty

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<fieldset>
    <legend>@Model.t_leki.nazwa_char</legend>

    <img src="../../Content/themes/base/images/image_3.png"  alt="brak"/><br />

    <span>Nazwa leku: </span> <b>@Model.t_leki.nazwa_char</b><br />
    <span>Cena: </span> <b>@Model.cena</b><br />
    <span>Opakowanie: </span> <b>@Model.t_leki.opak_char</b><br />
    <span>Nazwa sklepu:</span> <b>@Model.t_sklepy.Nazwa</b><br />
    <span>Dostępna ilość:</span> <b>@Model.ilosc</b><br />
    <br />
    @Html.ActionLink("Dodaj do koszyka", "AddToCart", "ShoppingCart", new { id = Model.Id, returnUrl = Request.Url }, new { @class = "addtocard" })
    <br />
</fieldset>
<p>
@if (Request.IsAuthenticated)
{
    if (Session["Admin"] == "Admin")
    {
        @Html.ActionLink("Edytuj", "Edit", new { id=Model.Id }) <p>|</p>
        @Html.ActionLink("Powrót do danych apteki", "Index")
    }
}
else
{
    @Html.ActionLink("Powrót", "Index", "Category")
}
</p>

Apteka/Views/Produkty/Edit.cshtml
@model Apteka.t_produkty

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Produkty apteki.</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.cena)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.cena)
            @Html.ValidationMessageFor(model => model.cena)
        </div>        

        <div class="editor-label">
            @Html.LabelFor(model => model.lek_id, "t_leki")
        </div>
        <div class="editor-field">
            @Html.DropDownList("lek_id", String.Empty)
            @Html.ValidationMessageFor(model => model.lek_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ilosc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ilosc)
            @Html.ValidationMessageFor(model => model.ilosc)
        </div>

        <p>
            <input type="submit" value="Zapisz" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

Apteka/Views/Produkty/Index.cshtml
@model IEnumerable<Apteka.t_produkty>

@{
    ViewBag.Title = "Index";
}

<h2>Produkty</h2>

<p>
    @Html.ActionLink("Dodaj produkt", "Create")
</p>
<table>
    <tr>
        <th>
            cena
        </th>
        <th>
            t_sklepy
        </th>
        <th>
            t_leki
        </th>
        <th>
            ilosc
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.t_sklepy.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.t_leki.nazwa_char)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ilosc)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Więcej", "Details", new { id=item.Id }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>